const CardActionTypes = {
    GET_DATA_CARDS: 'GET_DATA_CARDS',
    EDIT_CARD: 'EDIT_CARD',
    DELETE_CARD: 'DELETE_CARD',
    ADD_CARD: 'ADD_CARD',
    SELECTED_CARD: 'SELECTED_CARD',
    CLEAR_SELECTED_CARD: 'CLEAR_SELECTED_CARD',
    ORDER_BY_NAME: 'ORDER_BY_NAME',
    ORDER_BY_ID: 'ORDER_BY_ID'
}

export default CardActionTypes;